### PR TITLE
chore(ci): update GitHub Actions workflow

### PR DESCRIPTION
**Pull request by Fenrikur**

### CODE REVIEW

**Comment by lukashaertel** [comment]
Adding the translations in English to all other translations will remove the (valid) warning of the items being untranslated, I'm not sure we should do that

**Comment by Fenrikur** [comment]
> Adding the translations in English to all other translations will remove the (valid) warning of the items being untranslated, I'm not sure we should do that

Fair point (although there were already some English translations in these other files to begin with).
@Requinard wanted to set `--max-warnings=0` on all linting tasks, so its either this or accepting that at least the translation linter will have warnings. If we do not set that parameter on the translation linter, I'd simply remove all English translations from all language files (there were some in there before).

**Comment by lukashaertel** [comment]
Cleanest would be to remove the English translations that are not in .en, because we're pulling those from fallback English anyways, and if we have them in both we will likely forget to change them if we change the originals. So overall I'd like no max warnings on the translations until we all speak every translated language

**Comment by Fenrikur** [comment]
> Cleanest would be to remove the English translations that are not in .en, because we're pulling those from fallback English anyways, and if we have them in both we will likely forget to change them if we change the originals. So overall I'd like no max warnings on the translations until we all speak every translated language

Works fine for me, then I'll just remove that parameter from the translation linter entirely and strip all English translations from non-English translation files. (=

**Review by lukashaertel — APPROVED** [review]

**Pull request merged**
